"""Target-state and recommendation configuration for transformation planning."""

from __future__ import annotations


TARGET_STATES = {
    "Basic Foundation": {
        "description": "Establish minimal governance, roles, requirements process, basic testing and defect management.",
        "target_maturity": 2.0,
    },
    "Professional Delivery": {
        "description": "Standardized delivery process, clear quality ownership, structured testing, stable environments, metrics and initial automation.",
        "target_maturity": 3.0,
    },
    "Managed Quality Engineering": {
        "description": "Measured quality processes, active improvement, integrated tooling, automation strategy, reporting and release predictability.",
        "target_maturity": 4.0,
    },
    "Optimizing / Leading": {
        "description": "Continuous improvement, advanced automation, strong metrics, proactive quality governance, high delivery predictability.",
        "target_maturity": 5.0,
    },
}


WAVES = {
    "0-3 months": {
        "name": "Wave 1: 0-3 months - Foundation",
        "focus": "Ownership, governance, requirements, basic test process, defect process, and release discipline.",
    },
    "3-6 months": {
        "name": "Wave 2: 3-6 months - Standardization",
        "focus": "Standard test approach, test management tooling, environment stability, test data process, reporting, and reusable templates.",
    },
    "6-12 months": {
        "name": "Wave 3: 6-12 months - Industrialization",
        "focus": "Regression testing, test automation strategy, metrics dashboard, risk-based testing, quality gates, and training.",
    },
    "12+ months": {
        "name": "Wave 4: 12+ months - Optimization",
        "focus": "Automation scaling, continuous improvement, advanced quality metrics, ROI tracking, benchmarking, and predictable delivery.",
    },
}


BENEFIT_CATEGORIES = (
    "Improved release predictability",
    "Reduced defect leakage",
    "Better business-IT alignment",
    "Reduced manual testing effort",
    "Improved auditability",
    "Better decision-making through metrics",
    "Higher quality awareness",
    "Improved ROI on tooling and automation",
)


RECOMMENDATIONS = (
    {
        "domain": "Business & Governance",
        "title": "Appoint clear Product Ownership",
        "description": "Define accountable business ownership for prioritization, scope decisions and acceptance.",
        "wave": "0-3 months",
        "effort": "Medium",
        "business_value": "High",
        "dependency": "Management commitment",
        "expected_benefit": "Improved prioritization and reduced ambiguity in delivery.",
        "cgi_service_opportunity": "PO coaching, governance setup, delivery operating model.",
        "benefits": ("Better business-IT alignment", "Improved release predictability", "Higher quality awareness"),
    },
    {
        "domain": "Business & Governance",
        "title": "Introduce quality governance cadence",
        "description": "Create a lightweight governance rhythm to review quality risk, release readiness, and improvement actions.",
        "wave": "0-3 months",
        "effort": "Low",
        "business_value": "High",
        "dependency": "Named business and IT owners",
        "expected_benefit": "Faster decisions and more visible ownership of quality risks.",
        "cgi_service_opportunity": "Quality governance design, workshop facilitation.",
        "benefits": ("Improved auditability", "Better decision-making through metrics", "Improved release predictability"),
    },
    {
        "domain": "Requirements & Change Management",
        "title": "Standardize requirements and acceptance criteria",
        "description": "Define minimum requirements quality standards, acceptance criteria templates, and change impact checks.",
        "wave": "0-3 months",
        "effort": "Medium",
        "business_value": "High",
        "dependency": "Product owner and analyst participation",
        "expected_benefit": "Reduced ambiguity and fewer late-stage requirement defects.",
        "cgi_service_opportunity": "Requirements maturity uplift, BA coaching, template library.",
        "benefits": ("Better business-IT alignment", "Reduced defect leakage", "Improved release predictability"),
    },
    {
        "domain": "Requirements & Change Management",
        "title": "Implement end-to-end traceability",
        "description": "Connect requirements to tests, defects, releases, and business outcomes in the delivery toolchain.",
        "wave": "3-6 months",
        "effort": "Medium",
        "business_value": "Medium",
        "dependency": "Stable backlog and test management practices",
        "expected_benefit": "Clearer impact analysis and stronger audit evidence.",
        "cgi_service_opportunity": "ALM process design, traceability setup, reporting dashboards.",
        "benefits": ("Improved auditability", "Better decision-making through metrics"),
    },
    {
        "domain": "Development Process",
        "title": "Define delivery standards and quality gates",
        "description": "Agree minimum standards for code reviews, definition of done, release readiness, and engineering controls.",
        "wave": "0-3 months",
        "effort": "Medium",
        "business_value": "High",
        "dependency": "Engineering leadership alignment",
        "expected_benefit": "More consistent delivery quality across teams.",
        "cgi_service_opportunity": "Engineering operating model, quality gate design.",
        "benefits": ("Improved release predictability", "Reduced defect leakage", "Higher quality awareness"),
    },
    {
        "domain": "Development Process",
        "title": "Create technical debt and improvement backlog",
        "description": "Make architecture risks, technical debt, and engineering improvement items visible and prioritized.",
        "wave": "3-6 months",
        "effort": "Low",
        "business_value": "Medium",
        "dependency": "Architecture and delivery input",
        "expected_benefit": "Better prioritization of maintainability and reliability improvements.",
        "cgi_service_opportunity": "Technical debt assessment, architecture advisory.",
        "benefits": ("Improved release predictability", "Higher quality awareness"),
    },
    {
        "domain": "Testing & Quality",
        "title": "Establish risk-based test strategy",
        "description": "Define test levels, ownership, entry and exit criteria, and risk-based coverage expectations.",
        "wave": "0-3 months",
        "effort": "Medium",
        "business_value": "High",
        "dependency": "Product and engineering agreement on quality risks",
        "expected_benefit": "Testing effort is focused on the highest business and technical risks.",
        "cgi_service_opportunity": "Test strategy design, QA operating model, test lead coaching.",
        "benefits": ("Reduced defect leakage", "Improved release predictability", "Higher quality awareness"),
    },
    {
        "domain": "Testing & Quality",
        "title": "Build maintainable regression capability",
        "description": "Rationalize regression scope, remove obsolete tests, and align regression coverage to product risk.",
        "wave": "6-12 months",
        "effort": "Medium",
        "business_value": "High",
        "dependency": "Stable test inventory and defect history",
        "expected_benefit": "Improved confidence in releases without excessive manual retesting.",
        "cgi_service_opportunity": "Regression optimization, test portfolio review.",
        "benefits": ("Reduced defect leakage", "Reduced manual testing effort", "Improved release predictability"),
    },
    {
        "domain": "Test Data & Environments",
        "title": "Stabilize test environments",
        "description": "Create ownership, booking, monitoring, incident, and version visibility for key test environments.",
        "wave": "3-6 months",
        "effort": "Medium",
        "business_value": "High",
        "dependency": "Environment inventory and platform ownership",
        "expected_benefit": "Less delivery delay caused by unavailable or unreliable environments.",
        "cgi_service_opportunity": "Environment management setup, release and platform advisory.",
        "benefits": ("Improved release predictability", "Reduced manual testing effort"),
    },
    {
        "domain": "Test Data & Environments",
        "title": "Implement compliant test data process",
        "description": "Define test data request, masking, refresh, and reset processes for priority delivery flows.",
        "wave": "3-6 months",
        "effort": "High",
        "business_value": "Medium",
        "dependency": "Data ownership and privacy guidance",
        "expected_benefit": "More reliable testing with stronger compliance and audit evidence.",
        "cgi_service_opportunity": "Test data management, data masking advisory.",
        "benefits": ("Improved auditability", "Reduced manual testing effort", "Reduced defect leakage"),
    },
    {
        "domain": "Tooling & Automation",
        "title": "Define automation strategy and standards",
        "description": "Agree automation goals, scope, tooling standards, maintainability rules, and ownership model.",
        "wave": "6-12 months",
        "effort": "Medium",
        "business_value": "High",
        "dependency": "Stable test approach and CI/CD foundations",
        "expected_benefit": "Automation investment is focused and sustainable.",
        "cgi_service_opportunity": "Test automation strategy, tool selection, framework setup.",
        "benefits": ("Reduced manual testing effort", "Improved ROI on tooling and automation", "Improved release predictability"),
    },
    {
        "domain": "Tooling & Automation",
        "title": "Integrate quality checks into CI/CD",
        "description": "Embed automated tests, static analysis, security scans, and release checks into delivery pipelines.",
        "wave": "6-12 months",
        "effort": "High",
        "business_value": "High",
        "dependency": "Pipeline availability and engineering standards",
        "expected_benefit": "Earlier detection of quality issues and more repeatable release decisions.",
        "cgi_service_opportunity": "CI/CD quality engineering, DevSecOps enablement.",
        "benefits": ("Reduced defect leakage", "Improved release predictability", "Improved ROI on tooling and automation"),
    },
    {
        "domain": "Metrics & Reporting",
        "title": "Create quality and delivery metrics dashboard",
        "description": "Define a common metric set and dashboard for delivery health, defects, automation, release readiness, and improvement tracking.",
        "wave": "6-12 months",
        "effort": "Medium",
        "business_value": "High",
        "dependency": "Reliable source data and metric ownership",
        "expected_benefit": "Better decisions through consistent visibility of quality and delivery trends.",
        "cgi_service_opportunity": "Metrics framework, dashboard implementation, KPI advisory.",
        "benefits": ("Better decision-making through metrics", "Improved release predictability", "Improved auditability"),
    },
    {
        "domain": "Metrics & Reporting",
        "title": "Introduce continuous improvement reviews",
        "description": "Use metrics, incidents, retrospectives, and stakeholder feedback to prioritize improvement actions.",
        "wave": "12+ months",
        "effort": "Low",
        "business_value": "High",
        "dependency": "Baseline metrics and governance cadence",
        "expected_benefit": "Quality improvements become systematic instead of reactive.",
        "cgi_service_opportunity": "Continuous improvement model, quality coaching.",
        "benefits": ("Higher quality awareness", "Better decision-making through metrics", "Improved ROI on tooling and automation"),
    },
)
